# Generated by Django 3.1.6 on 2021-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=120)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'easy'), ('DIFFICULT', 'difficult')], default='EASY', max_length=20)),
            ],
        ),
    ]
