# Generated by Django 3.1.6 on 2021-10-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
